// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.FGL")>]
[<assembly: AssemblyProductAttribute("FSharp.FGL")>]
[<assembly: AssemblyDescriptionAttribute("Functional graph library for F#")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.FGL"
    let [<Literal>] AssemblyProduct = "FSharp.FGL"
    let [<Literal>] AssemblyDescription = "Functional graph library for F#"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
