image: 
  - Ubuntu
  - Visual Studio 2019

init:
  - git config --global core.autocrlf input

matrix:
  fast_finish: true

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  build_script:
  - cmd: fake.cmd -t fullBuildChainCI
-
  matrix:
    only:
      - image: Ubuntu

  build_script:
  - chmod +x ./fake.sh
  - sh: ./fake.sh -t dotnetBuildChainCI
  - sh: bash <(curl -s https://codecov.io/bash)

test: off
version: 0.0.1.{build}

branches:
  only:
    - developer

artifacts:
  - path: bin
    name: bin