// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.FGL.IO")>]
[<assembly: AssemblyProductAttribute("FSharp.FGL")>]
[<assembly: AssemblyDescriptionAttribute("Functional graph-library written in F#")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.FGL.IO"
    let [<Literal>] AssemblyProduct = "FSharp.FGL"
    let [<Literal>] AssemblyDescription = "Functional graph-library written in F#"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
